### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Immortalin** [nzaillian/django-encrypted-secrets#5]
```Python
  cwd: /tmp/pip-install-m3fxu64u/django-encrypted-secrets/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-m3fxu64u/django-encrypted-secrets/setup.py", line 4, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'README-pypi.md')) as readme:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-m3fxu64u/django-encrypted-secrets/README-pypi.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Immortalin** [comment]
Fixed by reverting: https://github.com/Immortalin/django-encrypted-secrets/commit/b7d498cba8908a0ba64969378f9fc4a6c4bcee65

**Comment by nzaillian** [comment]
@Immortalin very sorry about this. I fixed it now with the update here https://github.com/nzaillian/django-encrypted-secrets/commit/0d0fd6fb368d9d79c1370d2b7069a573418614fb, which is pushed as v. `0.9.7` (adding a manifest for setup.py to make sure the PyPI README gets picked up) and does seem to be working now
